version: '3.8'

services:
  youtube-bot:
    build: .
    container_name: youtube-downloader-bot
    env_file:
      - .env
    volumes:
      - ./app:/app
      - /data_hdd/media/movies:/app/downloads
      - ./temp_downloads:/app/temp_downloads
      - ./logs:/app/logs
      - ./allowed_users.json:/config/allowed_users.json
    restart: unless-stopped
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge